### ISSUE TITLE
Method for neovim-gnuplot highlight using your /syntax/gnuplot.vim file

### ISSUE THREAD

**Issue by luobinlin987** [dpezto/gnuplot.vim#1]
In fact, your effect for highlight of gnuplot files in neovim is almost done. Here is what I do.

1.  grab your /syntax/gnuplot.vim file to .config/nvim/syntax, intact.

2.  create a file .config/nvim/filetype.vim, and the content should be like:

if exists("did_load_filetypes")
  finish
endif
augroup filetypedetect
au! BufNewFile,BufRead *.plt,*.plot,*.gnuplot,*.gnu,*.gp setf gnuplot
augroup END

The method is the manual approach C of neovim document: new-filetype in https://neovim.io/doc/user/filetype.html#new-filetype

3. try any .gp file. I works for me now

**Comment by dpezto** [comment]
You're right, in fact I've migrated to lua and added this to my config:

```lua
vim.filetype.add({
  filename = {
    ["gnuplotrc"] = "gnuplot",
  },
  pattern = {
    ["${XDG_CONFIG_HOME}/gnuplot/Palettes/.*%.pal"] = "gnuplot",
  },
})

local gnuplot = { "plt", "plot", "gnuplot", "gnu", "gp" }
for _, ext in ipairs(gnuplot) do
  vim.filetype.add({ extension = { [ext] = "gnuplot" } })
end
```

On other note I haven't done much to this repo since I'm now using a [gnuplot syntax](https://github.com/dpezto/tree-sitter-gnuplot) I made for treesitter. Before I knew what treesitter was I tried to to the same effect using regex which is really slow.
Maybe in the future I'll update this repo for gnuplot 6.0 but remove most of the regex nonsense so that it's faster and usable.

**Comment by dpezto** [comment]
# Syntax highlight comparison
Default vim/neovim [gnuplot](https://github.com/neovim/neovim/blob/e9b53f3fb56e91a0d4f15bb36d8068bcc6ea88cf/runtime/syntax/gnuplot.vim) syntax file:
<img width="1512" alt="default" src="https://github.com/dpezto/gnuplot.vim/assets/32249161/ce1d6d38-a644-4ab8-b0f4-6e07d86f1a23">
[gnuplot.vim](https://github.com/dpezto/gnuplot.vim) Is much better at the expense of being painfully slow:
<img width="1512" alt="gnuplot vim" src="https://github.com/dpezto/gnuplot.vim/assets/32249161/0c8b9192-bc05-4c91-8a5e-03c9a2058545">
[tree-sitter-gnuplot](https://github.com/dpezto/tree-sitter-gnuplot) which is simply better in every way:
<img width="1512" alt="treesitter" src="https://github.com/dpezto/gnuplot.vim/assets/32249161/b492913b-ae28-42c6-9cbf-3e80d9147746">
